name: Generate CHANGELOG.md

on:
  push:
    tags:
      - '*'

permissions:
    contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate CHANGELOG.md
        uses: ganiulis/generate-changelog-action@main
        with:
          repository-name: generate-changelog-action

